apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: count-system-ingress
  namespace: count-system
spec:
  rules:
  - http:
      paths:
      - path: /api/v1/counts
        pathType: Prefix
        backend:
          service:
            name: count-write-service
            port:
              number: 3000
      - path: /management
        pathType: Prefix
        backend:
          service:
            name: count-management-service
            port:
              number: 3002
      - path: /analysis
        pathType: Prefix
        backend:
          service:
            name: count-analysis-service
            port:
              number: 3003
      - path: /dashboard/events
        pathType: Prefix
        backend:
          service:
            name: dashboard-update-service
            port:
              number: 3005
      - path: /dashboard
        pathType: Prefix
        backend:
          service:
            name: dashboard-provision-service
            port:
              number: 3004
